version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: k8s-slack-searcher
    binary: k8s-slack-searcher
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    # Windows ARM64 and CGO cross-compilation can be complex
    ignore:
      - goos: windows
        goarch: arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    # For CGO cross-compilation, we'll use the default Go toolchain
    # This works well for most common platforms

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - '^refactor:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: raesene
    name: k8s-slack-searcher
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Kubernetes Slack Searcher v{{.Version}}
    
    A command-line tool to index and search through Slack workspace archives.
    
    ### Installation
    
    Download the appropriate binary for your platform below, or install via Go:
    ```bash
    go install github.com/raesene/k8s-slack-searcher@{{.Tag}}
    ```
    
    ### Changes
  footer: |
    ### Docker Images
    
    Docker images are available at:
    ```bash
    docker pull ghcr.io/raesene/k8s-slack-searcher:{{.Tag}}
    ```
    
    **Full Changelog**: https://github.com/raesene/k8s-slack-searcher/compare/{{.PreviousTag}}...{{.Tag}}

# Docker images
dockers:
  - id: k8s-slack-searcher
    image_templates:
      - "ghcr.io/raesene/k8s-slack-searcher:{{ .Tag }}"
      - "ghcr.io/raesene/k8s-slack-searcher:v{{ .Major }}"
      - "ghcr.io/raesene/k8s-slack-searcher:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/raesene/k8s-slack-searcher:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/raesene/k8s-slack-searcher"
    extra_files:
      - LICENSE
      - README.md