project_name: k8s-slack-searcher

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: k8s-slack-searcher
    binary: k8s-slack-searcher
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: linux
        goarch: arm64
      - goos: windows
        goarch: arm64
      - goos: darwin
        goarch: amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    builds:
      - k8s-slack-searcher
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^build:'
      - '^style:'
      - '^refactor:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: raesene
    name: k8s-slack-searcher
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## Kubernetes Slack Searcher v{{.Version}}
    
    A command-line tool to index and search through Slack workspace archives.
    
    ### Installation
    
    Download the appropriate binary for your platform below, or install via Go:
    ```bash
    go install github.com/raesene/k8s-slack-searcher@{{.Tag}}
    ```
    
    ### Changes
  footer: |
    **Full Changelog**: https://github.com/raesene/k8s-slack-searcher/compare/{{.PreviousTag}}...{{.Tag}}